"""Add column 'multipleMessagee' for class mailboxMessage

Revision ID: 06d7318d1f94
Revises: 655d1f0c803c
Create Date: 2022-06-15 22:29:41.070649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d7318d1f94'
down_revision = '655d1f0c803c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox_message', sa.Column('multipleMessage', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox_message', 'multipleMessage')
    # ### end Alembic commands ###
