"""empty message

Revision ID: 365a42d3a507
Revises: fd168d577674
Create Date: 2022-12-18 14:57:27.423696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365a42d3a507'
down_revision = 'fd168d577674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_bans', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_bans', 'description')
    # ### end Alembic commands ###
