"""New version for production

Revision ID: 48dd85ddad63
Revises: 
Create Date: 2022-07-14 18:12:25.059713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48dd85ddad63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('senderName', sa.String(length=50), nullable=True),
    sa.Column('receiver', sa.String(length=500), nullable=False),
    sa.Column('receiverName', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('sendByApp', sa.Boolean(), nullable=False),
    sa.Column('sendByEmail', sa.Boolean(), nullable=False),
    sa.Column('messageReaded', sa.Boolean(), nullable=False),
    sa.Column('multipleMessage', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('activities', sa.Column('stravaID', sa.BigInteger(), nullable=True))
    op.drop_column('activities', 'week')
    op.add_column('event', sa.Column('maxUserAmount', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('readMessage', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isAddedByGoogle', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isAddedByFB', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAddedByFB')
    op.drop_column('user', 'isAddedByGoogle')
    op.drop_column('user', 'readMessage')
    op.drop_column('event', 'maxUserAmount')
    op.add_column('activities', sa.Column('week', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('activities', 'stravaID')
    op.drop_table('mailbox_message')
    # ### end Alembic commands ###
