"""empty message

Revision ID: 546438e88438
Revises: ea93eb81e719
Create Date: 2022-11-18 13:38:37.072305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546438e88438'
down_revision = 'ea93eb81e719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('event', sa.Column('added_on', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('added_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'added_on')
    op.drop_column('event', 'added_on')
    op.drop_column('activities', 'added_on')
    # ### end Alembic commands ###
