"""Add column 'receiverName' for class mailboxMessage

Revision ID: 655d1f0c803c
Revises: 6edc8840ded8
Create Date: 2022-06-15 20:31:52.724689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655d1f0c803c'
down_revision = '6edc8840ded8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox_message', sa.Column('receiverName', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox_message', 'receiverName')
    # ### end Alembic commands ###
