"""Add column 'senderName' and 'messageReaded' for DB of mailbox

Revision ID: 6edc8840ded8
Revises: 9b35e77ce5ef
Create Date: 2022-06-13 21:49:10.631041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6edc8840ded8'
down_revision = '9b35e77ce5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox_message', sa.Column('senderName', sa.String(length=50), nullable=True))
    op.add_column('mailbox_message', sa.Column('messageReaded', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox_message', 'messageReaded')
    op.drop_column('mailbox_message', 'senderName')
    # ### end Alembic commands ###
