"""empty message

Revision ID: 712c961b867d
Revises: 546438e88438
Create Date: 2022-12-08 21:33:59.116288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '712c961b867d'
down_revision = '546438e88438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport', sa.Column('strava_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport', 'strava_name')
    # ### end Alembic commands ###
