"""Added column 'user.readMessage'

Revision ID: 7eee24b7c9f0
Revises: 8aac882c474e
Create Date: 2022-05-07 15:40:56.506395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eee24b7c9f0'
down_revision = '8aac882c474e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('readMessage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'readMessage')
    # ### end Alembic commands ###
