"""Max user of event added.

Revision ID: 8aac882c474e
Revises: c03160364a79
Create Date: 2022-05-06 17:32:54.323282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aac882c474e'
down_revision = 'c03160364a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('maxUserAmount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'maxUserAmount')
    # ### end Alembic commands ###
