"""Social media accounts column

Revision ID: 9b35e77ce5ef
Revises: 7eee24b7c9f0
Create Date: 2022-05-17 18:39:13.363705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b35e77ce5ef'
down_revision = '7eee24b7c9f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAddedByGoogle', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('isAddedByFB', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAddedByFB')
    op.drop_column('user', 'isAddedByGoogle')
    # ### end Alembic commands ###
