"""empty message

Revision ID: af8e5dbf47a6
Revises: 
Create Date: 2022-12-11 12:53:08.451865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8e5dbf47a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sport', sa.Column('strava_name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sport', 'strava_name')
    # ### end Alembic commands ###
