"""Initial migration.

Revision ID: c03160364a79
Revises: 
Create Date: 2022-05-06 17:13:42.619688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03160364a79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coefficients_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setName', sa.String(length=50), nullable=True),
    sa.Column('activityName', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('constant', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distances_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_ID', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('avatar', sa.LargeBinary(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('activity', sa.String(length=50), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('userName', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['userName'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('lengthWeeks', sa.Integer(), nullable=False),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('adminID', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('isPrivate', sa.Boolean(), nullable=False),
    sa.Column('isSecret', sa.Boolean(), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('coefficientsSetName', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['adminID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_name'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('event')
    op.drop_table('activities')
    op.drop_table('user')
    op.drop_table('distances_table')
    op.drop_table('coefficients_list')
    # ### end Alembic commands ###
